### ISSUE TITLE
SimpleCoverageInstrumentOptionDescriptors does not exist

### ISSUE THREAD

**Issue by ruanzhi** [graalvm/simpletool#10]
![image](https://user-images.githubusercontent.com/16523077/116327987-88941200-a7fa-11eb-9c4c-adad275a8e57.png)
Hello, I will pull the project from github into the idea and find that this class does not exist. Why is this? Is this casual?

**Comment by priyansh-07** [comment]
Hi @ruanzhi, I am getting the same issue, the docs mention some implicit information about this

> In order for this annotation to be effective the Truffle DSL processor needs to process this class. This is, in case of Simple Tool, done automatically by having the DSL processor as a dependency in the [maven configuration](https://github.com/graalvm/simpletool/blob/master/pom.xml#L83).

However, it is still not working in my case. The only difference is that I cloned this repo and migrated it to gradle since the project I am trying to integrate this with is in gradle, Can you please also mentioned how you were able to resolve this issue?

**Comment by wangxi761** [comment]
1. execute maven compile
2. add `target/generated-sources/annotations` to your IDE source path
3. it's okay
